### PR TITLE
Add reo.dev analytics to documentation

### PR DESCRIPTION
**Pull request by lykinsbd**

### CODE REVIEW

**Comment by ogenstad** [comment]
Do we want to remove plausible.io when we add this?

**Comment by dgarros** [comment]
> Do we want to remove plausible.io when we add this?

Nope, they are complementary

**Comment by dgarros** [comment]
I think we should cherry pick this commit into stable

**Comment by lykinsbd** [comment]
I have a PR open to bring it into Stable as well: https://github.com/opsmill/infrahub/pull/4660

**Pull request merged**
