### PR TITLE
Remove filters from the schema

### LINKED ISSUE #4373: feature: Remove the list of available filters from the schema
### Component

API Server / GraphQL

### Describe the Feature Request

Currently, a list of available filters is integrated as part of the schema for each model. 

image

This information was initially used by the frontend to display the right filters in a list view and by the Python SDK to do some local validation. Today the frontend is not using it anymore and there are some discussion to stop using them in the SKD as well because the information in the schema aren't always up to date with what is supported in the SDK.

Considering the challenges to maintain a separate list of query filters accurately, the low usage of this information and the additional size of the schema due to these filters, I think we should remove them entirely.

### Describe the Use Case

Housekeeping  and reducing the size of the schema 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dgarros**
Fixes #4373

This PR completely removes the filters from the schema. 
Based on CodSpeed's result there is a significant performance improvement,  much better than i expected

### CODE REVIEW

**Review by ajtmccarty — APPROVED** [review]

**Comment by fatih-acar** [comment]
@dgarros the improvement is expected because filters relied on massive usage of hashing functions and that was one of the major CPU bottlenecks in the code... this is great :)

**Comment by fatih-acar** [comment]
And the CI's benchmark job is now almost 2 times faster... :tada:

**Comment by ogenstad** [comment]
> the improvement is expected because filters relied on massive usage of hashing functions and that was one of the major CPU bottlenecks in the code... this is great :)

Do we have other examples of those functions where we suffer due to the hashing? Is it worth checking for alternate ways of hashing?

**Comment by fatih-acar** [comment]
> > the improvement is expected because filters relied on massive usage of hashing functions and that was one of the major CPU bottlenecks in the code... this is great :)
> 
> Do we have other examples of those functions where we suffer due to the hashing? Is it worth checking for alternate ways of hashing?

I don't think there's a way to know which code paths lead to CPU exhaustion due to hashing, but we can introduce new benchmark tests that make use of known hashing code paths.

If I take one of the benchmark test result that have improved with this PR here: https://codspeed.io/opsmill/infrahub/branches/dga-20241003-filters

image

You can see that the main CPU bottleneck in `SchemaBranch.process_filters` was the `deepcopy` stuff (we already tried to reduce as much as possible these calls) and the `BaseNodeSchema.get_hash` calls.
What we could do is finding all the intensive and/or recursive callers to `BaseNodeSchema.get_hash` and write a benchmark test for them?

Regarding the hashing itself, I think we currently use MD5 and I already tried CRC32 instead in the past (and other "faster" hashing algorithms) and it didn't help much. But there's probably ways to improve that too.

**Pull request merged**
