### PR TITLE
Fix serialization for ComputedAttribute in schema

### PR DESCRIPTION
**Pull request by dgarros**

### CODE REVIEW

**Comment by ogenstad** [comment]
Currently this fails when trying to load a schema.

Using an example schema like this:

```yaml

# yaml-language-server: $schema=https://schema.infrahub.app/develop/schema.schema.json
---
version: '1.0'

nodes:
  - name: Character
    namespace: Rpg
    label: "Character"
    icon: "mdi:shield-person"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: slug
        kind: Text
        description: "Lowercase"
        computed_attribute:
          kind: Jinja2
          jinja2_template: "{{ name__value|lower }}"
        read_only: true
        optional: false
```

infrahubctl returns a 500 error.

```bash
❯ infrahubctl schema load ../models/computed_basic.yml
HTTP communication failure: Server error '500 Internal Server Error' for url 'http://localhost:8000/api/schema/load?branch=main'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500 on POST to http://localhost:8000/api/schema/load?branch=main
```


In Prefect we get this for `schema_validate_migrations`

```python
Worker 'InfrahubWorkerAsync 675fc8c0-5bfc-4b87-be5b-2dae814649f1' submitting flow run '8dba3b54-2368-41c5-aa22-2297a40dcafb'
04:26:45 PM
prefect.flow_runs.worker
Failed to submit flow run '8dba3b54-2368-41c5-aa22-2297a40dcafb' to infrastructure.
Traceback (most recent call last):
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.12/site-packages/prefect/workers/base.py", line 883, in _submit_run_and_capture_errors
    result = await self.run(
             ^^^^^^^^^^^^^^^
  File "/Users/patrick/Code/opsmill/infrahub/backend/infrahub/workers/infrahub_async.py", line 137, in run
    params = flow_func.validate_parameters(parameters=flow_run.parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.12/site-packages/prefect/flows.py", line 591, in validate_parameters
    raise ParameterTypeError.from_validation_error(exc) from None
prefect.exceptions.ParameterTypeError: Flow run received invalid parameters:
 - message.schema_branch.attributes.3.computed_attribute.kind: Field required
 - message.schema_branch.attributes.3.computed_attribute.value: Extra inputs are not permitted
04:26:45 PM
prefect.flow_runs.worker
Reported flow run '8dba3b54-2368-41c5-aa22-2297a40dcafb' as crashed: Flow run could not be submitted to infrastructure
```

**Comment by ogenstad** [comment]
I opened #4905 to fix this, need to look at it some more. Also it feels like a bit of a hack :(

**Comment by dgarros** [comment]
> I opened #4905 to fix this, need to look at it some more. Also it feels like a bit of a hack :(

ah sorry I didn't realize you were also working on it
I just pushed a fix to this branch I think it should be good now

**Comment by ogenstad** [comment]
> ah sorry I didn't realize you were also working on it I just pushed a fix to this branch I think it should be good now

Oh, no worries. Your solution looks a lot cleaner. We still have to fix the issue of the hashing as it doesn't pick up that the schema has changed if you only change the computed attribute. But let's do that in another PR.

**Review by ogenstad — APPROVED** [review]

**Comment by dgarros** [comment]
> Oh, no worries. Your solution looks a lot cleaner. We still have to fix the issue of the hashing as it doesn't pick up that the schema has changed if you only change the computed attribute. But let's do that in another PR.

I'll send a fix for that tomorrow

**Pull request merged**
