### PR TITLE
Update resource manager documentation

### PR DESCRIPTION
**Pull request by BaptisteGi**
- Add number pool to the documentation
- Refactor resource manager page to create section for each type of pool
- Various changes and improvements

### CODE REVIEW

**Comment by BaptisteGi** [comment]
fyi @fatih-acar just changed the documentation here but I see that it triggers the e2e tests, is it intended that way?

**Comment by BaptisteGi** [comment]
> fyi @fatih-acar just changed the documentation here but I see that it triggers the e2e tests, is it intended that way?

aaah for screenshots right?

**Comment by fatih-acar** [comment]
> > fyi @fatih-acar just changed the documentation here but I see that it triggers the e2e tests, is it intended that way?
> 
> aaah for screenshots right?

We use the E2E tests to generate screenshots, but not through the CI as far as I remember... we run them locally for screenshots.
I think we can disable running the E2E tests for documentation changes, you are right
cc @wartraxx51

**Review by BeArchiTek — APPROVED** [review]

**Comment by dgarros** [comment]
looks like we forgot to change the destination branch for this PR, it needs to go in `release-1.0` to be part of the release or if there is nothing specific to the release it could go directly into `stable`

**Pull request merged**
