### PR TITLE
set up plumbing and documentation for `towncrier`

### PR DESCRIPTION
**Pull request by lykinsbd**

### CODE REVIEW

**Comment by lykinsbd** [comment]
[Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) made many changes to the `pyproject.toml` file. I asked in Slack if we want to leave this as it's in our recommended VS Code extensions in the docs.

**Comment by lykinsbd** [comment]
It also looks like the [MDX](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx) VSCode extension runs ESLint, which also lines/formats .ts files (in this case the sidebar.ts file).

**Comment by lykinsbd** [comment]
Closes #4023

**Comment by ogenstad** [comment]
LGTM overall though the vale.sh CI job to validate style is failing (https://github.com/opsmill/infrahub/actions/runs/10273073557/job/28426779000?pr=4021), can you take a look at that?

**Review by ogenstad — APPROVED** [review]

**Pull request merged**
