### PR TITLE
allow to customize postgres service and image source

### PR DESCRIPTION
**Pull request by DisasteR**
allow deployment of infrahub when using a docker registry proxy.
and customization of postgres auth

Will affect ansible install role when propagated to https://infrahub.opsmill.io/

### CODE REVIEW

**Review by dgarros — COMMENTED** [review]
The changes looks good to me but I think the changes need to be integrated into the `stable` branch, not `develop` to show up in https://infrahub.opsmill.io/
Do you mind cherry picking your commit into a new branch based on `stable`
thanks

**Review by BeArchiTek — CHANGES_REQUESTED** [review]
Thank you for your PR @DisasteR !

LGTM. I do have a small remark on my side, I don't think we should add those in `x-infrahub-config` but create another anchor dedicated to task-manager configuration

**Comment by DisasteR** [comment]
@BeArchiTek  I'll try that.
I'll send an update ASAP

**Comment by DisasteR** [comment]
if everything is ok for you i'll send a PR on the stable branch

**Comment by BeArchiTek** [comment]
LGTM for the changes, you can redo a PR to stable 👍

**Comment by DisasteR** [comment]
Submitted PR #4851

**Comment by BeArchiTek** [comment]
https://github.com/opsmill/infrahub/pull/4851 has been merged. I will cherry-pick stable to develop and close this PR to avoid conflict.

**Pull request closed without merging**
