### PR TITLE
Remove at parameter from graph QL mutations

### LINKED ISSUE #3587: task: Remove `at` parameter from GraphQL mutations
### Component

API Server / GraphQL

### Task Description

In these examples as well as other places we're passing `at` using the context value. For mutations this shouldn't be used as we don't support create, update, delete operations based on a timestamp. As such any parameter for `at` within the mutations can be removed.

```python
class InfrahubMutationMixin:
    @classmethod
    async def mutate(cls, root: dict, info: GraphQLResolveInfo, *args, **kwargs):
        context: GraphqlContext = info.context

        obj = None
        mutation = None
        action = MutationAction.UNDEFINED
        validate_mutation_permissions(operation=cls.__name__, account_session=context.account_session)

        if "Create" in cls.__name__:
            obj, mutation = await cls.mutate_create(
                root=root, info=info, branch=context.branch, at=context.at, **kwargs
            )
            action = MutationAction.ADDED
        elif "Update" in cls.__name__:
            obj, mutation = await cls.mutate_update(
                root=root, info=info, branch=context.branch, at=context.at, **kwargs
            )
            action = MutationAction.UPDATED
```

An extra bonus in this case is that it would clean up some typehint issues. The above is just an example we have the same issue in other mutations too not just the generic mixin one.

### PR DESCRIPTION
**Pull request by PhillSimonds**
Fixes #3587

### CODE REVIEW

**Comment by PhillSimonds** [comment]
Unittest error flagged in CI doesn't occur locally.

```
infrahub-server-py3.12➜  infrahub git:(ps-issue-3587) pytest -s -vv backend/tests/unit/graphql/mutations/
... truncated for brevity
===================== 1 passed in 26.60s =====================
Time: 0h:00m:31s                                                        
```

I'm unsure of how to proceed.

**Comment by ogenstad** [comment]
It's probably an issue related to memgraph if you're testing with neo4j locally. I can try to take a look tomorrow to see if I can figure out what's going on.

**Comment by PhillSimonds** [comment]
Ahhh, ok cool. I was using neo4j, will try with memgraph.

**Comment by ogenstad** [comment]
Hey, just wanted to check if you were waiting for me here. As you wrote that you'd check with memgraph I didn't do anything more. Completely understand if you've just been doing other things, just wanted to see if you were waiting for my input?

**Comment by PhillSimonds** [comment]
Hey Patrick!

Sorry for my delay here on getting back. I used memgraph with similar problems. Unit test when run alone with memgraph backend doesn't show any problems. When I run the full python test file I don't see any problems either. But when I run the full suite of unit tests I see issues. My hunch is there is some sort of state leak from another test or something.

**Comment by ogenstad** [comment]
So, we decided to disable the Memgraph test just now (or yesterday). Can you rebase your branch and push it again? Then we can see if the tests pass without the memgraph checks.

**Comment by PhillSimonds** [comment]
Acknowledged. Merged in develop :)

**Comment by ogenstad** [comment]
FYI @PhillSimonds, looks like this one had some linting issues in the CI, and now also a merge conflict.

**Comment by PhillSimonds** [comment]
Aye thanks, looks like I forgot to blacken the code after merging develop and resolving conflicts. Looks like it's good now 🤞🏻

**Review by ogenstad — APPROVED** [review]
Thanks! Looks good to me.

**Pull request merged**
